services:
  - type: web
    name: crypto-ai-bot-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main_server:app --host=0.0.0.0 --port=8000"
    plan: free
    region: singapore
    autoDeploy: true
