services:
  - type: web
    name: yopo-ai
    env: python
    plan: standard  # ✅ 여기만 'free' → 'standard' 로 변경
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    healthCheckPath: /ping
